spring.application.name=teste

spring.config.import=optional:file:.env[.properties] 
telegram.bot.token=${TELEGRAM_BOT_TOKEN}
telegram.chat.id=${TELEGRAM_CHAT_ID}

# Porta da aplicação Spring Boot
server.port=3000

gmail.username=${GMAIL_USERNAME:}
gmail.app.password=${GMAIL_APP_PASSWORD:}


gmail.subject.file=ultimo_assunto.txt

